### ISSUE TITLE
想請您幫忙寫個讀K-type的温感的ui

### ISSUE THREAD

**Issue by linhaoping** [oscarcx123/oscarcx123.github.io#3]
找了网上的Python的代码,可以在樹梅派上讀出K-Type的温度,但是想要有個UI用来显示更舒服些,希望能请您帮忙有偿的,我的联系方式 linhaoping@苹果的云.com  谢谢

**Comment by oscarcx123** [comment]
很抱歉，我帮不上忙。树莓派的话应该装的是Raspbian，你要的可能是xfce plugin，可以看看xfce wiki上的[Xfce Panel Plugins How To](https://wiki.xfce.org/dev/howto/panel_plugins)

**Comment by linhaoping** [comment]
Dear Sir
谢谢您的回复
因为我也没写过程序, 我就是依照网路上的一些文章  在树梅派上接了 MAX6675 模块
依照下列范例  ,自己修改了范例代码里的GPIO pin脚, 在树梅派上也能读出来
https://github.com/archemius/MAX6675-Raspberry-pi-python <https://github.com/archemius/MAX6675-Raspberry-pi-python>


执行后的画面


其实这样我已经可以用, 就是想著如果能是个简单画面小程序就更好
看了些文章好像说用QT开发的多  于是看见您发表的文章箱依照您的文章下去做
事实证明还是啥都看不懂


这是我构想的ui画面  就是开始或结束的按钮
剩下的就是显示返回来的max6675模块的值
不知道该如何著手
整个介面宽有384就可以   长就看实际需求了
因为现在在用的设备调试器是用树梅派开发的
但是得另外外接一个温度显示设备   非常不方便  尤其是隔个房间的时候
做在树梅派上我就可以方便些
现在也能用, 就试希望能更美观些
不会任何语言, 所以想请专家协助看看
如果能有个范例了, 或许以后可以自己慢慢研究或开发更多
看看您能否帮忙,费用看多少钱  我当教学费
谢谢您

Best Regards,
David Lin





> 2020年8月20日 08:04，oscarcx123 <notifications@github.com> 写道：
> 
> Xfce Panel Plugins How To <https://wiki.xfce.org/dev/howto/panel_plugins>

**Comment by oscarcx123** [comment]
我确实有个树莓派3b+，但是已经吃灰很久了，所以我没有这方面的折腾经验可以分享。。。我猜你可能是在csdn上看到我那个pyqt教程找来的吧，反正我不是专家，真正的大佬哪有空在网上水博客文章😂

你给的图片看不到，在markdown一般是`![](url)`这种形式。

我开始以为你是需要xfce上的控件，但是看起来你只是要显示模块返回的温度值，那就ssh远程连接树莓派，命令行执行代码。虽然你描述的GUI很简单，但是不建议搞，那样还要给树莓派接个屏幕。

我的建议仅供参考，实际情况需要自行权衡。
