### ISSUE TITLE
非常感谢博主撰写的 Shenzhen I/O  的文章

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [oscarcx123/oscarcx123.github.io#4]
文章写的很好，讲解了逻辑构思，并介绍代码技巧。
并且本文是我发现唯一全用推荐器件的分享，非常适合初学者。
我是在优化 Lv.12 时，卡住十几个小时，才发现的这篇文章，+ 50 这个思路，真是惊为天人。
按这个路线，比之前的设计有大幅度优化。
电量 1081  --> 740
代码  26    -->  16
另外 优化后的设计，比博主目前的版本稍好些，希望博主能更新文章，方便大家。😋

老设计：
![image](https://user-images.githubusercontent.com/10376283/183786485-d0e88a1a-1070-4c38-8b0b-367f3c9317fc.png)

新设计：
![image](https://user-images.githubusercontent.com/10376283/183786881-e129df6f-f036-4dbc-a331-3b0dcd7f5f46.png)

 
```
  tgt p1 79
- tgt 20 p1
+ mov 30  acc
+ jmp 1
  tgt 40 p1
+ jmp 1
  tgt 80 p0
+ tgt p0 39
+ add 50
  tgt p1 59
+ add 30 
1:mov acc x2
  mov 0 acc 
  slp 1
```
 

```
  slx x0
  mov x0 p1
```

**Comment by wy16W2pIilK1xgqN** [comment]
一个QQ群友，告诉我一个更牛逼的，人外有人、天外有天呀🤡
<img width="929" alt="image" src="https://user-images.githubusercontent.com/10376283/183788273-d867af99-3154-428f-af97-508ed39bc79c.png">

**Comment by oscarcx123** [comment]
真意外，居然有人看👀
谢谢夸奖，这篇文章当时是用来记录思路的，能帮上忙就没白写😋
优化的解法也已经更新了，如果你有其它常用id/称呼的话可以提供一下，`Wof3YldPjOvDh9xe`也太长了

**Comment by wy16W2pIilK1xgqN** [comment]
墙外就这个ID了。请见谅。

**Comment by oscarcx123** [comment]
OK，能理解，那我关issue了
